server:
  port: 8090
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop_logger?serverTimezone=UTC
    username: root
    password: 355286888aaAA!!@@##$$%%