spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop?serverTimezone=UTC
    username: root
    password: 355286888aaAA!!@@##$$%%
  flyway:
    baseline-on-migrate: true