server:
  port: 8880
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DATABASE_PATH_SHOP_MYSQL}
    username: ${DATABASE_USER_SHOP_MYSQL}
    password: ${DATABASE_PASSWORD_SHOP_MYSQL}
  flyway:
    baseline-on-migrate: true